// Sample posts with real BUBT student names for initial feed
// These will be replaced with actual Supabase data when available

export const SAMPLE_POSTS = [
  {
    id: 1,
    user: {
      name: 'Md. Tahmid Bin Masud',
      department: 'Computer Science & Engineering',
    },
    content: 'Just deployed my first full-stack web application! Spent 3 months working on it. The feeling of seeing it live is incredible. Thanks to everyone who helped me debug along the way! 🚀💻',
    category: 'General',
    timestamp: '1h ago',
    likes: 42,
    comments: 15,
  },
  {
    id: 2,
    user: {
      name: 'Jannatul Ferdous Mim',
      department: 'Business Administration',
    },
    content: 'Our team just won first prize in the National Business Plan Competition! Hard work, dedication, and teamwork really pays off. Grateful for this amazing journey! 🏆✨',
    category: 'Announcements',
    timestamp: '3h ago',
    likes: 128,
    comments: 34,
  },
  {
    id: 3,
    user: {
      name: 'Sultan Ahmmed',
      department: 'Software Engineering',
    },
    content: 'Does anyone have the slides from yesterday\'s Machine Learning lecture? My laptop crashed and I lost all my notes. Would really appreciate it if someone could share! 🙏',
    category: 'Questions',
    timestamp: '4h ago',
    likes: 18,
    comments: 23,
  },
  {
    id: 4,
    user: {
      name: 'Sumya Akter',
      department: 'Graphic Design',
    },
    content: 'Excited to showcase my digital art portfolio at the university\'s Creative Arts Exhibition next Friday! Come check out the artwork and support fellow artists. See you there! 🎨💫',
    category: 'Events',
    timestamp: '6h ago',
    likes: 89,
    comments: 28,
  },
  {
    id: 5,
    user: {
      name: 'Raduan Abdullah Ishrak',
      department: 'Computer Science & Engineering',
    },
    content: 'Looking for 2 more developers to join our hackathon team this weekend. We\'re building an AI-powered study assistant app. Experience with React Native is a plus! DM me if interested.',
    category: 'General',
    timestamp: '8h ago',
    likes: 56,
    comments: 19,
  },
  {
    id: 6,
    user: {
      name: 'Sadia Haque Noor',
      department: 'Psychology',
    },
    content: 'Reminder: Mental Health Awareness Workshop tomorrow at 3 PM in the main auditorium. We\'ll discuss stress management techniques and coping strategies. All students welcome! 🧠💚',
    category: 'Events',
    timestamp: '12h ago',
    likes: 145,
    comments: 42,
  },
  {
    id: 7,
    user: {
      name: 'Md Jobayer Hossan',
      department: 'Computer Science & Engineering',
    },
    content: 'I got accepted into Google Summer of Code 2024! Dreams really do come true with consistent effort and dedication. Never give up on your goals! 💪🎉',
    category: 'Announcements',
    timestamp: '1d ago',
    likes: 267,
    comments: 58,
  },
  {
    id: 8,
    user: {
      name: 'Nusrat Jahan Nabila',
      department: 'English Literature',
    },
    content: 'Starting a weekly book club meeting every Thursday at the library. This week we\'re discussing "The Kite Runner". Everyone who loves reading is welcome to join us! 📚',
    category: 'Events',
    timestamp: '1d ago',
    likes: 73,
    comments: 21,
  },
  {
    id: 9,
    user: {
      name: 'Hasibur Rahman',
      department: 'Electrical & Electronic Engineering',
    },
    content: 'Working on a solar-powered mobile charging station project for the campus. Looking for team members interested in renewable energy. Let\'s make our campus greener! ☀️',
    category: 'General',
    timestamp: '1d ago',
    likes: 94,
    comments: 27,
  },
  {
    id: 10,
    user: {
      name: 'Raisha Zaman',
      department: 'Architecture',
    },
    content: 'Our architecture exhibition "Urban Dreams" opens this Saturday! Come see innovative designs for sustainable city planning. Free entry for all students! 🏗️✨',
    category: 'Events',
    timestamp: '2d ago',
    likes: 112,
    comments: 33,
  },
  {
    id: 11,
    user: {
      name: 'Omar Faruk Fahim',
      department: 'Computer Science & Engineering',
    },
    content: 'Free Python programming workshop this Sunday from 2-5 PM in Lab 301. Perfect for beginners! Bring your laptop and let\'s code together. Limited seats available!',
    category: 'Events',
    timestamp: '2d ago',
    likes: 156,
    comments: 45,
  },
  {
    id: 12,
    user: {
      name: 'Maysha Hossain',
      department: 'Fashion Design',
    },
    content: 'Just launched my sustainable fashion collection! Using eco-friendly materials to create beautiful designs. Check out my Instagram page for the full collection. Supporting local artisans! 👗🌿',
    category: 'General',
    timestamp: '2d ago',
    likes: 187,
    comments: 52,
  },
  {
    id: 13,
    user: {
      name: 'Tarikul Islam',
      department: 'Mathematics',
    },
    content: 'Offering free tutoring sessions for Calculus and Linear Algebra every Saturday at the library from 10 AM. Exam season is coming, let\'s prepare together! No fees, just bring your questions 📐',
    category: 'Announcements',
    timestamp: '3d ago',
    likes: 203,
    comments: 67,
  },
  {
    id: 14,
    user: {
      name: 'Nabil Mohaimin',
      department: 'Civil Engineering',
    },
    content: 'Our civil engineering project on earthquake-resistant buildings got selected for the national conference! Thanks to my amazing team for the hard work. Innovation in action! 🏢',
    category: 'Announcements',
    timestamp: '3d ago',
    likes: 145,
    comments: 38,
  },
  {
    id: 15,
    user: {
      name: 'Syeda Adiba Noshin',
      department: 'Pharmacy',
    },
    content: 'Completed my internship at Square Pharmaceuticals! Learned so much about drug formulation and quality control. Grateful for this incredible experience! 💊🔬',
    category: 'General',
    timestamp: '3d ago',
    likes: 98,
    comments: 24,
  },
  {
    id: 16,
    user: {
      name: 'Md. Rakibul Islam',
      department: 'Marketing',
    },
    content: 'Looking for creative minds to join our digital marketing club. We\'re planning some exciting campaigns for local businesses. Great opportunity to build your portfolio!',
    category: 'General',
    timestamp: '4d ago',
    likes: 76,
    comments: 29,
  },
  {
    id: 17,
    user: {
      name: 'Ruqayya Haque',
      department: 'Law',
    },
    content: 'Moot Court Competition registration is now open! This is a great opportunity to enhance your legal skills and network with professionals. Deadline: Next Friday. Don\'t miss out! ⚖️',
    category: 'Announcements',
    timestamp: '4d ago',
    likes: 132,
    comments: 41,
  },
  {
    id: 18,
    user: {
      name: 'Ahmad Yasir Rahat',
      department: 'Computer Science & Engineering',
    },
    content: 'Anyone interested in forming a competitive programming team? ICPC is coming up and I\'d love to train together. Let\'s solve problems and improve our coding skills! 💻',
    category: 'General',
    timestamp: '5d ago',
    likes: 84,
    comments: 32,
  },
  {
    id: 19,
    user: {
      name: 'Farzia Tasnim',
      department: 'Journalism & Media Studies',
    },
    content: 'Our campus magazine is looking for writers, photographers, and designers! If you have a creative side and want to share your voice, join us. DM for details! 📰',
    category: 'General',
    timestamp: '5d ago',
    likes: 67,
    comments: 18,
  },
  {
    id: 20,
    user: {
      name: 'Md. Redwan Hossain',
      department: 'Robotics & Automation',
    },
    content: 'Just completed my line-following robot project! It can navigate complex mazes autonomously. Thanks to the Robotics Club for the support. Next goal: autonomous drone! 🤖',
    category: 'General',
    timestamp: '6d ago',
    likes: 156,
    comments: 44,
  },
];

